gText_Birch_Welcome::
	.string "A quanto pare un altro candidato s'è\n"
	.string "presentato al Centro d'Accoglienza!\p"
	.string "Benvenuto a Jujjonia: Luogo di\n"
	.string "residenza del Plotone Jujjesco.\p"
	.string "Il mio nome è CUM.\n"
	.string "Ma tutti mi chiamano il PROFESSOR\l"
	.string "SPERMA.\p"
	.string "Non penso di doverti introdurre al\n"
	.string "concetto di “POKéMON”..\p"
	.string "Cioè, se proprio volessi, potrei\n"
	.string "spiegarti cosa sono gli EV e gli IV\l"
	.string "oppure le Nature..\p"
	.string "Ma.. dal tuo sguardo vedo che non ti\n"
	.string "interessa troppo, quindi sorvoliamo.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "A proposito.. sapevi che, in\n"
	.string "termini di riproduzione tra umani\l"
	.string "e POKéMON, Vaporeon è il più com-$"

gText_Birch_MainSpeech::
	.string "NARRATORE: Per motivi di disgusto\n"
	.string "disdegno, e dispregio verso la\l"
	.string "zoofilia, skipperò interamente\l"
	.string "il precedente dialogo.\p"
	.string "(cough) TRANSIZIONE!1!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "PROF. CUM: Maledetta censura..\p"
	.string "Vabbè senti tagliamo corto.$"

gText_Birch_BoyOrGirl::
	.string "Sei una Chiave?\n"
	.string "O sei una Porta?$"

gText_Birch_WhatsYourName::
	.string "Mi fa piacere..\n"
	.string "E il nome, invece?$"

gText_Birch_SoItsPlayer::
	.string "Quindi ti chiami {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, ho capito.\p"
	.string "Quindi sei {PLAYER}{KUN}: l'ennesimo\n"
	.string "rincoglionito che vuole provare ad\l"
	.string "entrare nel Plotone Jujjesco.\l"
	.string "Ora capisco!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "In bocca al lupo per tutto, e\n"
	.string "ricordati di venirmi a trovare nel mio\l"
	.string "LABORATORIO.\p"
	.string "Magari riuscirò finalmente a\n"
	.string "raccontarti la lore di Vaporeon-$"
